### ISSUE TITLE
Support for V14

### ISSUE THREAD

**Issue by heruan** [vaadin/observability-kit#143]
This issue tracks the progress of adding support to Observability Kit for Vaadin Platform V14.

**Comment by MatthewVaadin** [comment]
PROBLEM: The `HttpStatusCode` class is not part of V14 and is used several times within the Kit code and tests.

SOLUTION: Replace with `HttpServletResponse` constants.

**Comment by MatthewVaadin** [comment]
PROBLEM: The `MockVaadinService` class used in the tests does not implement the correct method signatures for V14.

SOLUTION: Implement the correct method signatures (as well as retaining the V23 signatures).

**Comment by MatthewVaadin** [comment]
PROBLEM: When testing against V14, there is an exception saying that the push mode cannot be `null`.

SOLUTION: In the `MockVaadinService`, mock `DeploymentConfiguration.getPushMode()` to return `PushMode.DISABLED`.

**Comment by MatthewVaadin** [comment]
PROBLEM: When testing against V14, the `AbstractInstrumentationTest` class does not compile. The number of arguments for `mockUI.getInternals().showRouteTarget()` is incorrect.

SOLUTION: Add a new `path` argument with value `/test-route`.

NOTE: This will cause a compilation error when compiling against V23, so a more permanent solution may be required.

**Comment by MatthewVaadin** [comment]
PROBLEM: The V14 version of the bakery app does not output any traces.

NO SOLUTION

NOTE: According to some debug output on the `SessionRequestHandlerInstrumentation` class, the instrumentation hooks are being called (`classLoaderOptimization()`, `typeMatcher()`, and `transform()`), but the `onMethodEnter()` and `onMethodExit()` methods are not. Need to investigate further as to why this is.

**Comment by heruan** [comment]
Delivered in #145
