### ISSUE TITLE
Ensure frontend instrumentation is producing meaningful traces

### ISSUE THREAD

**Issue by tarekoraby** [vaadin/observability-kit#152]
After client-side instrumentation is implemented (#149), we need to ensure that the traces and metrics produced by the frontend agent are meaningful and actionable for the developers and admins of Flow apps. 

As a first step towards that end, I suggest creating an exemplary Flow app with security, a couple of master-detail views, push, and preserve-on-refresh. We can then analyze the traces of the frontend agent when the app is running normally, and when it experiences some errors or performance degradations.

**Comment by mcollovati** [comment]
The demo application may also contain some client-side views/components that raise errors randomly and perform heavy tasks simulating browser slow-down and freezes

On the observability side, it would be nice to associate user-agent information along with the collected traces and metrics. OpenTelemetry should already have something if I recall correctly.

For the Flow client, it may be interesting to collect metrics on UIDL parsing and handling. There is already information logged on the console, but it would be nice to collect them as OpenTelemetry metrics.
