### ISSUE TITLE
Frontend observability documentation

### ISSUE THREAD

**Issue by heruan** [vaadin/observability-kit#170]
Proper documentation for the frontend observability module should be provided.

- [ ] What frontend observability provides (metrics/traces)
- [ ] How to enable frontend observability

**Comment by heruan** [comment]
PR: https://github.com/vaadin/docs/pull/2281

**Comment by MatthewVaadin** [comment]
https://github.com/vaadin/docs/pull/2281 is now merged.

**Comment by heruan** [comment]
Closed in https://github.com/vaadin/docs/pull/2393
