### ISSUE TITLE
Observability Kit does not work with Java 21

### ISSUE THREAD

**Issue by vesanieminen** [vaadin/observability-kit#260]
Currently Observability Kit currently does not work with Java 21. Here's the logs I'm getting currently with `-Dotel.javaagent.debug=true` in order to see also debug mode logs as well:
[o11y-error1.txt](https://github.com/user-attachments/files/17107963/o11y-error1.txt)

Using `-Dnet.bytebuddy.experimental=true` does not fare any better:
[o11y-error2.txt](https://github.com/user-attachments/files/17107968/o11y-error2.txt)

I made [commit in my forked repo](https://github.com/vesanieminen/observability-kit/commit/5322df19db6fab8c233bb90e910cd4f5f81ddb2a) where I updated the versions minimally in order to get Observability Kit running with Java 21. The tests I just forcefully "fixed" in order to get the project compiling but they don't work as is.

**Comment by jorgheymans** [comment]
related to https://github.com/vaadin/observability-kit/issues/259 i would say
