### ISSUE TITLE
Add handling of push

### ISSUE THREAD

**Issue by caalador** [vaadin/observability-kit#69]
At the moment if push is enabled there are a lot of error traces like:
![image](https://user-images.githubusercontent.com/2726090/187170996-8351d878-7255-4e12-9ecc-31932e2cac32.png)

Investigate how to handle/catch these instances.

**Comment by heruan** [comment]
Closed as [abandoned](https://github.com/vaadin/observability-kit/pull/75#issuecomment-1239030286).
